// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyA3PXvfHYafacx39fehu2JZ_AEp5_G1Nhc',
  //   appId: '1:988784061055:web:0d94d644f40750dc106d4a',
  //   messagingSenderId: '988784061055',
  //   projectId: 'cse489proj',
  //   authDomain: 'cse489proj.firebaseapp.com',
  //   databaseURL: 'https://cse489proj-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'cse489proj.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuLmcBhB1BCfVG8c8ayC4s5kSjl13PYYQ',
    appId: '1:988784061055:android:22c00804dae500d0106d4a',
    messagingSenderId: '988784061055',
    projectId: 'cse489proj',
    databaseURL:
        'https://cse489proj-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cse489proj.appspot.com',
  );
}
